name: Dependency Check (SCA)

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
    
      - name: Cache Maven packages
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      
      - name: Build with Maven
        working-directory: ./WebGoat
        run: mvn clean install
        
      - name: Run Dependency Check
        working-directory: ./WebGoat
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload HTML file
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: dependency-check-report
          # A file, directory or wildcard pattern that describes what to upload
          path: ./WebGoat/target/dependency-check-report.html
