name: Gitleaks (Secrets detector)
on:
  push:
    branches: ["main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.0
          
      # Upload SARIF file generated in previous step like CodeQL vulns
      - name: Upload vulns to CodeQL
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks-results.sarif
